### ISSUE TITLE
이게 Spring에서 실제 DB에 연결할 때 사용하는 방식인가요...?

### ISSUE THREAD

**Issue by P3RP** [P3RP/Winter-Is-End#22]
https://github.com/P3RP/Winter-Is-End/blob/2465c49fffe07cb946facc38c8a0910eec205dd6/inhun/week2/src/main/java/com/inhun/springboot/model/Articles.java#L13

**Comment by kkminseok** [comment]
@P3RP 
Getter, Setter 등 어노테이션은 lombok이라는 플러그인에서 지원합니다. 개발자가 Get()함수, Set()함수를 만들기 귀찮을 때, lombok에서 저 어노테이션 달면 알아서 만들어주는겁니다. 제가 공부할 땐 아무래도 Setter는 set()함수와 같아서 잘 사용하지는 않지만 조회용으로 Getter는 꽤 쓰는걸로 압니당.

**Comment by freckie** [comment]
`org.projectlombok:lombok`
